package com.quizbackend.quiz.receipt;

import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Port of the Node reference's {@code attempt-receipt.ts} issue/verify
 * functions. The receipt identifies ONE attempt at ONE quiz and carries the
 * whole-quiz deadline; per-question timing is {@link QuestionReceiptSigner}'s
 * job.
 *
 * <p>The field order in {@link #issue} is deliberately explicit ({@code v,
 * quizId, startedAt, expiresAt}) and matches the Node object literal's own
 * property order exactly — {@code ReceiptCodec.encodeSignedReceipt} signs
 * the JSON serialization of this exact map, so key order changes the
 * signature. Cross-language byte parity is proven in {@code
 * AttemptReceiptSignerTest} against strings actually generated by Node.
 */
@Component
public class AttemptReceiptSigner {

    private final ReceiptCodec codec;

    public AttemptReceiptSigner(ReceiptCodec codec) {
        this.codec = codec;
    }

    public String issue(AttemptReceiptPayload payload, String secret) {
        Map<String, Object> ordered = new LinkedHashMap<>();
        ordered.put("v", payload.v());
        ordered.put("quizId", payload.quizId());
        ordered.put("startedAt", payload.startedAt());
        ordered.put("expiresAt", payload.expiresAt());
        return codec.encodeSignedReceipt(ordered, secret);
    }

    /**
     * Verify and decode. Throws {@link AttemptReceiptException} on ANY
     * problem, always with the same message — a caller must not be able to
     * tell a tampered payload from a bad signature from a malformed string.
     *
     * <p>Deliberately does NOT check expiry: a receipt past its deadline is
     * still authentic, and the caller (the question-start route) decides
     * what to do with that — exactly like Node's {@code
     * verifyAttemptReceipt}, whose own test suite asserts "does NOT reject
     * on expiry — expiry is the CALLER's decision".
     */
    public AttemptReceiptPayload verify(String receipt, String secret) {
        Map<String, Object> parsed = codec.decodeSignedReceipt(receipt, secret).orElseThrow(AttemptReceiptException::new);

        Object v = parsed.get("v");
        Object quizId = parsed.get("quizId");
        Object startedAt = parsed.get("startedAt");
        Object expiresAt = parsed.get("expiresAt");

        if (!(v instanceof Number vNum) || vNum.intValue() != ReceiptCodec.RECEIPT_VERSION) {
            throw new AttemptReceiptException();
        }
        if (!(quizId instanceof String quizIdStr) || quizIdStr.trim().isEmpty()) {
            throw new AttemptReceiptException();
        }
        long startedAtValue = requireFinitePositiveLong(startedAt);
        long expiresAtValue = requireFiniteLong(expiresAt);
        if (expiresAtValue <= startedAtValue) {
            throw new AttemptReceiptException();
        }

        return new AttemptReceiptPayload(vNum.intValue(), quizIdStr, startedAtValue, expiresAtValue);
    }

    private static long requireFinitePositiveLong(Object value) {
        long result = requireFiniteLong(value);
        if (result <= 0) {
            throw new AttemptReceiptException();
        }
        return result;
    }

    private static long requireFiniteLong(Object value) {
        if (!(value instanceof Number number)) {
            throw new AttemptReceiptException();
        }
        double asDouble = number.doubleValue();
        if (Double.isNaN(asDouble) || Double.isInfinite(asDouble)) {
            throw new AttemptReceiptException();
        }
        return number.longValue();
    }

    /** For tests/diagnostics only — never use for an authorization decision. */
    public Object decodeUnverified(String receipt) {
        return codec.decodeReceiptUnverified(receipt);
    }
}
