package com.quizbackend.quiz.receipt;

import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Port of the Node reference's {@code question-receipt.ts} issue/verify
 * functions. One question's countdown — the Topic Quiz timer is
 * per-question, so this, not the attempt receipt, is what authorizes a
 * reveal by expiry.
 *
 * <p>Field order in {@link #issue} ({@code v, quizId, questionText,
 * startedAt, expiresAt}) matches Node's object literal exactly — see
 * {@link AttemptReceiptSigner}'s javadoc for why this matters for the
 * signature. Cross-language byte parity proven in {@code
 * QuestionReceiptSignerTest} against strings actually generated by Node.
 */
@Component
public class QuestionReceiptSigner {

    /** One question's countdown, matching the Angular {@code timePerQuestion}. */
    public static final int QUESTION_DURATION_SECONDS = 30;

    private final ReceiptCodec codec;

    public QuestionReceiptSigner(ReceiptCodec codec) {
        this.codec = codec;
    }

    public String issue(QuestionReceiptPayload payload, String secret) {
        Map<String, Object> ordered = new LinkedHashMap<>();
        ordered.put("v", payload.v());
        ordered.put("quizId", payload.quizId());
        ordered.put("questionText", payload.questionText());
        ordered.put("startedAt", payload.startedAt());
        ordered.put("expiresAt", payload.expiresAt());
        return codec.encodeSignedReceipt(ordered, secret);
    }

    /**
     * Verify and decode. Throws {@link QuestionReceiptException} on ANY
     * problem, always with the same message.
     */
    public QuestionReceiptPayload verify(String receipt, String secret) {
        Map<String, Object> parsed = codec.decodeSignedReceipt(receipt, secret).orElseThrow(QuestionReceiptException::new);

        Object v = parsed.get("v");
        Object quizId = parsed.get("quizId");
        Object questionText = parsed.get("questionText");
        Object startedAt = parsed.get("startedAt");
        Object expiresAt = parsed.get("expiresAt");

        if (!(v instanceof Number vNum) || vNum.intValue() != ReceiptCodec.RECEIPT_VERSION) {
            throw new QuestionReceiptException();
        }
        if (!(quizId instanceof String quizIdStr) || quizIdStr.trim().isEmpty()) {
            throw new QuestionReceiptException();
        }
        if (!(questionText instanceof String questionTextStr) || questionTextStr.trim().isEmpty()) {
            throw new QuestionReceiptException();
        }
        long startedAtValue = requireFinitePositiveLong(startedAt);
        long expiresAtValue = requireFiniteLong(expiresAt);
        if (expiresAtValue <= startedAtValue) {
            throw new QuestionReceiptException();
        }

        return new QuestionReceiptPayload(vNum.intValue(), quizIdStr, questionTextStr, startedAtValue, expiresAtValue);
    }

    private static long requireFinitePositiveLong(Object value) {
        long result = requireFiniteLong(value);
        if (result <= 0) {
            throw new QuestionReceiptException();
        }
        return result;
    }

    private static long requireFiniteLong(Object value) {
        if (!(value instanceof Number number)) {
            throw new QuestionReceiptException();
        }
        double asDouble = number.doubleValue();
        if (Double.isNaN(asDouble) || Double.isInfinite(asDouble)) {
            throw new QuestionReceiptException();
        }
        return number.longValue();
    }

    /** For tests/diagnostics only — never use for an authorization decision. */
    public Object decodeUnverified(String receipt) {
        return codec.decodeReceiptUnverified(receipt);
    }
}
