package com.quizbackend.quiz.receipt;

import org.springframework.stereotype.Component;
import tools.jackson.databind.ObjectMapper;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Optional;

/**
 * Signing primitives shared by every Topic Quiz receipt type &mdash; port of
 * the Node reference's {@code backend/src/quiz/receipt-codec.ts}.
 *
 * <p>Extracted so the attempt receipt and the per-question receipt cannot
 * drift apart: one base64url implementation, one HMAC, one constant-time
 * compare. A second hand-rolled copy of this is exactly how a signature
 * check quietly stops being constant-time.
 *
 * <p>The payloads these sign are readable on purpose (base64url JSON, not
 * encrypted) &mdash; see {@code AttemptReceiptSigner}/{@code
 * QuestionReceiptSigner} for why integrity rather than confidentiality is
 * the goal, matching Node's own documented reasoning.
 *
 * <p>Cross-language byte parity with Node is proven in {@code
 * ReceiptCodecTest} using receipt strings generated by actually running
 * Node's compiled {@code issueAttemptReceipt}/{@code issueQuestionReceipt}
 * for fixed synthetic inputs, not by re-deriving the format independently.
 */
@Component
public final class ReceiptCodec {

    public static final int RECEIPT_VERSION = 1;

    /** Receipts are small; anything larger is not a receipt we issued. */
    private static final int MAX_RECEIPT_LENGTH = 4096;

    private static final Base64.Encoder URL_ENCODER = Base64.getUrlEncoder().withoutPadding();
    private static final Base64.Decoder URL_DECODER = Base64.getUrlDecoder();

    private final ObjectMapper objectMapper;

    public ReceiptCodec(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    public static String base64UrlEncode(byte[] value) {
        return URL_ENCODER.encodeToString(value);
    }

    /**
     * Restore standard base64 padding before decoding, exactly like Node's
     * {@code base64UrlDecode} pads to a multiple of 4 &mdash; Java's decoder
     * requires this even though Node's runtime does not.
     */
    public static byte[] base64UrlDecode(String value) {
        String padded = value + "=".repeat((4 - (value.length() % 4)) % 4);
        return URL_DECODER.decode(padded);
    }

    private static byte[] sign(String encodedPayload, String secret) {
        try {
            Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8), "HmacSHA256"));
            return mac.doFinal(encodedPayload.getBytes(StandardCharsets.UTF_8));
        } catch (NoSuchAlgorithmException | InvalidKeyException e) {
            // HmacSHA256 is a mandatory JDK algorithm; a valid UTF-8 key is
            // always acceptable. Unreachable in practice.
            throw new IllegalStateException(e);
        }
    }

    /**
     * Constant-time signature comparison, using the JDK's canonical
     * constant-time primitive rather than {@code String.equals} &mdash; the
     * exact Java analogue of Node's {@code crypto.timingSafeEqual}. A length
     * mismatch is checked first and is not itself a timing oracle: the
     * signature length is fixed by SHA-256 and public.
     */
    private static boolean signaturesMatch(byte[] expected, byte[] actual) {
        if (expected.length != actual.length) {
            return false;
        }
        return MessageDigest.isEqual(expected, actual);
    }

    /**
     * Build the signed receipt string from an EXPLICITLY ORDERED field map.
     * The caller supplies a {@link LinkedHashMap} in the exact same key
     * order Node's object-literal payload uses, so the serialized JSON —
     * and therefore the signature — is byte-identical to what Node would
     * produce for the same field values.
     */
    public String encodeSignedReceipt(Map<String, Object> orderedPayload, String secret) {
        String json = objectMapper.writeValueAsString(orderedPayload);
        String encoded = base64UrlEncode(json.getBytes(StandardCharsets.UTF_8));
        String signature = base64UrlEncode(sign(encoded, secret));
        return encoded + "." + signature;
    }

    /**
     * Verify the signature and return the raw decoded payload as a
     * String-keyed map, or {@link Optional#empty()} on ANY problem.
     *
     * <p>Callers must not distinguish the failure modes: a tampered
     * payload, a bad signature and a malformed string have to look
     * identical, or the difference tells an attacker how close they got.
     * The signature is checked BEFORE the payload is parsed &mdash; an
     * unverified payload is attacker-controlled input.
     */
    public Optional<Map<String, Object>> decodeSignedReceipt(String receipt, String secret) {
        if (receipt == null || receipt.isEmpty() || receipt.length() > MAX_RECEIPT_LENGTH) {
            return Optional.empty();
        }

        String[] parts = receipt.split("\\.", -1);
        if (parts.length != 2) {
            return Optional.empty();
        }
        String encodedPayload = parts[0];
        String providedSignature = parts[1];
        if (encodedPayload.isEmpty() || providedSignature.isEmpty()) {
            return Optional.empty();
        }

        byte[] expectedSignature = sign(encodedPayload, secret);
        byte[] actualSignature;
        try {
            actualSignature = base64UrlDecode(providedSignature);
        } catch (IllegalArgumentException notBase64) {
            return Optional.empty();
        }
        if (!signaturesMatch(expectedSignature, actualSignature)) {
            return Optional.empty();
        }

        Object parsed;
        try {
            byte[] decoded = base64UrlDecode(encodedPayload);
            parsed = objectMapper.readValue(decoded, Object.class);
        } catch (RuntimeException malformed) {
            return Optional.empty();
        }

        if (!(parsed instanceof Map)) {
            return Optional.empty();
        }
        @SuppressWarnings("unchecked")
        Map<String, Object> map = (Map<String, Object>) parsed;
        return Optional.of(map);
    }

    /**
     * Read a payload WITHOUT verifying &mdash; for tests and diagnostics
     * only. Never use this to make an authorization decision.
     */
    public Object decodeReceiptUnverified(String receipt) {
        String encoded = receipt.contains(".") ? receipt.substring(0, receipt.indexOf('.')) : "";
        return objectMapper.readValue(base64UrlDecode(encoded), Object.class);
    }
}
