package com.quizbackend.quiz.receipt;

import org.junit.jupiter.api.Test;
import tools.jackson.databind.ObjectMapper;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Cross-language + structural proof for {@link AttemptReceiptSigner} —
 * port of the Node reference's {@code attempt-receipt.ts}.
 *
 * <p><b>Cross-language byte parity</b>: {@link #EXPECTED_NODE_RECEIPT} was
 * captured by ACTUALLY RUNNING Node's compiled {@code issueAttemptReceipt}
 * (backend/dist/src/quiz/attempt-receipt.js, which itself calls the real
 * {@code receipt-codec.ts}) against the fixed synthetic payload/secret
 * below, via {@code node -e "require('./dist/src/quiz/attempt-receipt.js')..."}
 * in this session — not reimplemented or guessed. Spring reproducing the
 * IDENTICAL string proves the HMAC-SHA256 signing, base64url encoding, and
 * JSON field order all agree byte-for-byte with the live Node
 * implementation, not merely "look similar".
 */
class AttemptReceiptSignerTest {

    private static final String SECRET = "test-secret-at-least-thirty-two-chars-long";
    private static final String OTHER_SECRET = "a-completely-different-secret-also-long-enough";
    private static final long STARTED = 1_700_000_000_000L;
    private static final long EXPIRES = STARTED + 300_000L;

    /** Generated by real Node (backend/dist), payload {v:1,quizId:'rxjs',startedAt:STARTED,expiresAt:EXPIRES}. */
    private static final String EXPECTED_NODE_RECEIPT =
            "eyJ2IjoxLCJxdWl6SWQiOiJyeGpzIiwic3RhcnRlZEF0IjoxNzAwMDAwMDAwMDAwLCJleHBpcmVzQXQiOjE3MDAwMDAzMDAwMDB9"
                    + ".6d8m5TYcCgL_84_TDVIfx_-HJ44BkAZTnU7MSR_Aajs";

    private final AttemptReceiptSigner signer = new AttemptReceiptSigner(new ReceiptCodec(new ObjectMapper()));

    private static AttemptReceiptPayload payload() {
        return new AttemptReceiptPayload(ReceiptCodec.RECEIPT_VERSION, "rxjs", STARTED, EXPIRES);
    }

    @Test
    void issuedReceiptIsByteIdenticalToTheRealNodeImplementationForTheSameInput() {
        assertThat(signer.issue(payload(), SECRET)).isEqualTo(EXPECTED_NODE_RECEIPT);
    }

    @Test
    void aRealNodeIssuedReceiptVerifiesSuccessfullyAgainstTheSpringSigner() {
        AttemptReceiptPayload verified = signer.verify(EXPECTED_NODE_RECEIPT, SECRET);
        assertThat(verified).isEqualTo(payload());
    }

    @Test
    void producesATwoPartPayloadDotSignatureReceipt() {
        String receipt = signer.issue(payload(), SECRET);
        assertThat(receipt.split("\\.", -1)).hasSize(2);
    }

    @Test
    void isBase64UrlSafeNoPlusSlashOrEquals() {
        String receipt = signer.issue(new AttemptReceiptPayload(1, "a-quiz-with-plenty-of-bytes", STARTED, EXPIRES), SECRET);
        assertThat(receipt).matches("^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$");
    }

    @Test
    void isDeterministicForFixedInputSameInputSameReceipt() {
        assertThat(signer.issue(payload(), SECRET)).isEqualTo(signer.issue(payload(), SECRET));
    }

    @Test
    void neverEmbedsTheSecretInTheReceipt() {
        assertThat(signer.issue(payload(), SECRET)).doesNotContain(SECRET);
    }

    @Test
    void roundTripsAValidReceipt() {
        String receipt = signer.issue(payload(), SECRET);
        assertThat(signer.verify(receipt, SECRET)).isEqualTo(payload());
    }

    @Test
    void rejectsATamperedPayload() {
        String receipt = signer.issue(payload(), SECRET);
        String signature = receipt.split("\\.")[1];
        String forgedPayload = ReceiptCodec.base64UrlEncode(
                "{\"v\":1,\"quizId\":\"rxjs\",\"startedAt\":1700000000000,\"expiresAt\":1786400300000}"
                        .getBytes(java.nio.charset.StandardCharsets.UTF_8));
        assertThatThrownBy(() -> signer.verify(forgedPayload + "." + signature, SECRET))
                .isInstanceOf(AttemptReceiptException.class);
    }

    @Test
    void rejectsATamperedSignature() {
        String receipt = signer.issue(payload(), SECRET);
        String[] parts = receipt.split("\\.");
        char flipped = parts[1].charAt(0) == 'A' ? 'B' : 'A';
        String tampered = parts[0] + "." + flipped + parts[1].substring(1);
        assertThatThrownBy(() -> signer.verify(tampered, SECRET)).isInstanceOf(AttemptReceiptException.class);
    }

    @Test
    void rejectsAReceiptSignedWithADifferentSecret() {
        String receipt = signer.issue(payload(), OTHER_SECRET);
        assertThatThrownBy(() -> signer.verify(receipt, SECRET)).isInstanceOf(AttemptReceiptException.class);
    }

    @Test
    void rejectsMalformedReceiptsOfEveryShape() {
        for (String malformed : new String[] {
                "", "abcdef", "a.b.c", ".signature", "payload.", "!!!.???"
        }) {
            assertThatThrownBy(() -> signer.verify(malformed, SECRET))
                    .isInstanceOf(AttemptReceiptException.class);
        }
        assertThatThrownBy(() -> signer.verify(null, SECRET)).isInstanceOf(AttemptReceiptException.class);
    }

    @Test
    void rejectsAnAbsurdlyLongReceiptWithoutParsingIt() {
        String tooLong = "a".repeat(5000) + ".sig";
        assertThatThrownBy(() -> signer.verify(tooLong, SECRET)).isInstanceOf(AttemptReceiptException.class);
    }

    @Test
    void rejectsAValidlySignedPayloadWithAnUnknownVersion() {
        String receipt = signWithRawFields(1_700_000_000_000L, EXPIRES, "rxjs", 99);
        assertThatThrownBy(() -> signer.verify(receipt, SECRET)).isInstanceOf(AttemptReceiptException.class);
    }

    @Test
    void rejectsExpiresAtNotAfterStartedAt() {
        String receipt = signWithRawFields(STARTED, STARTED, "rxjs", 1);
        assertThatThrownBy(() -> signer.verify(receipt, SECRET)).isInstanceOf(AttemptReceiptException.class);

        String receiptBefore = signWithRawFields(STARTED, STARTED - 1, "rxjs", 1);
        assertThatThrownBy(() -> signer.verify(receiptBefore, SECRET)).isInstanceOf(AttemptReceiptException.class);
    }

    @Test
    void doesNotRejectOnExpiryExpiryIsTheCallersDecision() {
        // A receipt past its own deadline is still authentic — the CALLER
        // (question-start route) decides what that means, exactly like
        // Node's own documented behavior.
        AttemptReceiptPayload alreadyExpired = new AttemptReceiptPayload(1, "rxjs", 1L, 2L);
        String receipt = signer.issue(alreadyExpired, SECRET);
        assertThat(signer.verify(receipt, SECRET).expiresAt()).isEqualTo(2L);
    }

    @Test
    void returnsOnlyTheFourKnownFieldsDiscardingSmuggledExtras() throws Exception {
        // Sign a payload with EXTRA fields (isCorrect/questionId) using the raw
        // codec directly — verify() must still return only the 4 known fields.
        var codec = new ReceiptCodec(new ObjectMapper());
        java.util.LinkedHashMap<String, Object> smuggled = new java.util.LinkedHashMap<>();
        smuggled.put("v", 1);
        smuggled.put("quizId", "rxjs");
        smuggled.put("startedAt", STARTED);
        smuggled.put("expiresAt", EXPIRES);
        smuggled.put("isCorrect", true);
        smuggled.put("questionId", "rxjs:q:0");
        String receipt = codec.encodeSignedReceipt(smuggled, SECRET);

        AttemptReceiptPayload verified = signer.verify(receipt, SECRET);
        assertThat(verified).isEqualTo(payload());
    }

    @Test
    void givesTheSameMessageForEveryFailureNoOracle() {
        java.util.Set<String> messages = new java.util.HashSet<>();
        for (String bad : new String[] { "", "a.b.c", "garbage" }) {
            try {
                signer.verify(bad, SECRET);
            } catch (AttemptReceiptException e) {
                messages.add(e.getMessage());
            }
        }
        try {
            signer.verify(signer.issue(payload(), OTHER_SECRET), SECRET);
        } catch (AttemptReceiptException e) {
            messages.add(e.getMessage());
        }
        assertThat(messages).hasSize(1);
    }

    @Test
    void neverMentionsTheSecretInAnError() {
        try {
            signer.verify("bad.receipt", SECRET);
        } catch (AttemptReceiptException e) {
            assertThat(e.getMessage()).doesNotContain(SECRET);
        }
    }

    /** Builds a validly-signed receipt with fields the payload() helper cannot represent (e.g. an unknown version). */
    private String signWithRawFields(long startedAt, long expiresAt, String quizId, int version) {
        var codec = new ReceiptCodec(new ObjectMapper());
        java.util.LinkedHashMap<String, Object> raw = new java.util.LinkedHashMap<>();
        raw.put("v", version);
        raw.put("quizId", quizId);
        raw.put("startedAt", startedAt);
        raw.put("expiresAt", expiresAt);
        return codec.encodeSignedReceipt(raw, SECRET);
    }
}
